export default {
  USER: {
    ENTER_TOKEN: 'ENTER_TOKEN',
    SAVE_TOKEN: 'SAVE_TOKEN',
  },
  REPOS: {
    UPDATE_REPOS: 'UPDATE_REPOS',
  },
  ISSUES: {
    UPDATE_ISSUES: 'UPDATE_ISSUES',
    FETCHING_ISSUES: 'FETCHING_ISSUES',
    RESET_REPO_SELECTED: 'RESET_REPO_SELECTED',
  },
  ERRORS: {
    SHOW_ERROR: 'SHOW_ERROR',
    HIDE_ERROR: 'HIDE_ERROR',
  }
}